[W 2024-02-13 13:30:05.503 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-02-13 13:30:05.505 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-02-13 13:30:05.517 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-02-13 13:30:05.529 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-02-13 13:30:05.540 ServerApp] notebook | extension was successfully linked.
[I 2024-02-13 13:30:05.792 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-02-13 13:30:05.830 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-02-13 13:30:05.832 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-02-13 13:30:05.833 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-02-13 13:30:05.836 LabApp] JupyterLab extension loaded from /export/scratch2/home/savvina/new_environment/conda/envs/elliot_env/lib/python3.8/site-packages/jupyterlab
[I 2024-02-13 13:30:05.836 LabApp] JupyterLab application directory is /export/scratch2/home/savvina/new_environment/conda/envs/elliot_env/share/jupyter/lab
[I 2024-02-13 13:30:05.837 LabApp] Extension Manager is 'pypi'.
[I 2024-02-13 13:30:05.840 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-02-13 13:30:05.843 ServerApp] notebook | extension was successfully loaded.
[I 2024-02-13 13:30:05.844 ServerApp] Serving notebooks from local directory: /export/scratch2/home/savvina/new_environment/Elliot
[I 2024-02-13 13:30:05.844 ServerApp] Jupyter Server 2.12.5 is running at:
[I 2024-02-13 13:30:05.844 ServerApp] http://localhost:8888/tree?token=380f82803d9189adec861a1cc64c7f3a0e302727398d7326
[I 2024-02-13 13:30:05.844 ServerApp]     http://127.0.0.1:8888/tree?token=380f82803d9189adec861a1cc64c7f3a0e302727398d7326
[I 2024-02-13 13:30:05.844 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-02-13 13:30:05.847 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///export/scratch2/home/savvina/.local/share/jupyter/runtime/jpserver-60446-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/tree?token=380f82803d9189adec861a1cc64c7f3a0e302727398d7326
        http://127.0.0.1:8888/tree?token=380f82803d9189adec861a1cc64c7f3a0e302727398d7326
[I 2024-02-13 13:30:07.897 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2024-02-13 13:30:47.131 ServerApp] 302 GET /?token=[secret] (@127.0.0.1) 1.53ms
[W 2024-02-13 13:31:16.060 ServerApp] Clearing invalid/expired login cookie username-127-0-0-1-8888
[I 2024-02-13 13:31:16.061 JupyterNotebookApp] 302 GET /tree (@127.0.0.1) 1.90ms
[I 2024-02-13 13:31:25.850 ServerApp] User b05ce82a73d844b4a0a11c10edf6043f logged in.
[I 2024-02-13 13:31:25.851 ServerApp] 302 POST /login?next=%2Ftree (b05ce82a73d844b4a0a11c10edf6043f@127.0.0.1) 2.35ms
[I 2024-02-13 13:37:04.493 ServerApp] Creating new notebook in 
[I 2024-02-13 13:37:11.181 ServerApp] Kernel started: 710d78a4-6ba7-40ab-ab52-dc24877f2249
[I 2024-02-13 13:37:11.807 ServerApp] Connecting to kernel 710d78a4-6ba7-40ab-ab52-dc24877f2249.
[I 2024-02-13 13:39:06.849 ServerApp] Saving file at /First try.ipynb
[I 2024-02-13 13:41:06.952 ServerApp] Saving file at /First try.ipynb
[I 2024-02-13 13:43:07.015 ServerApp] Saving file at /First try.ipynb
[I 2024-02-13 13:45:07.062 ServerApp] Saving file at /First try.ipynb
[I 2024-02-13 13:46:42.759 ServerApp] Kernel restarted: 710d78a4-6ba7-40ab-ab52-dc24877f2249
[I 2024-02-13 13:46:42.775 ServerApp] Starting buffering for 710d78a4-6ba7-40ab-ab52-dc24877f2249:2ffafce9-586a-419c-8fa2-61c0d7d36157
[I 2024-02-13 13:46:42.792 ServerApp] Connecting to kernel 710d78a4-6ba7-40ab-ab52-dc24877f2249.
[I 2024-02-13 13:46:42.792 ServerApp] Restoring connection for 710d78a4-6ba7-40ab-ab52-dc24877f2249:2ffafce9-586a-419c-8fa2-61c0d7d36157
[I 2024-02-13 13:47:07.119 ServerApp] Saving file at /First try.ipynb
2024-02-13 13:48:27.340718: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-13 13:48:27.340764: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[I 2024-02-13 13:49:07.172 ServerApp] Saving file at /First try.ipynb
[I 2024-02-13 13:51:08.065 ServerApp] Saving file at /First try.ipynb
[I 2024-02-13 13:53:09.057 ServerApp] Saving file at /First try.ipynb
[I 2024-02-13 13:53:34.215 ServerApp] Creating new file in /elliot/config_files
[I 2024-02-13 13:56:49.277 ServerApp] Copying First try.ipynb to 
[I 2024-02-13 13:56:52.210 ServerApp] Starting buffering for 710d78a4-6ba7-40ab-ab52-dc24877f2249:2ffafce9-586a-419c-8fa2-61c0d7d36157
[I 2024-02-13 13:56:52.830 ServerApp] Kernel started: 426060dc-bf09-4904-ab96-c21f6cda5563
[I 2024-02-13 13:56:53.513 ServerApp] Connecting to kernel 426060dc-bf09-4904-ab96-c21f6cda5563.
[I 2024-02-13 13:58:16.163 ServerApp] Saving file at /elliot/config_files/sample_hello_world.yml
[I 2024-02-13 13:58:18.149 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-13 13:58:52.724 ServerApp] Saving file at /Second try.ipynb
2024-02-13 13:59:14.998721: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-13 13:59:14.998770: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[I 2024-02-13 13:59:37.506 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-13 14:00:52.780 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-13 14:02:52.843 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-13 14:04:51.141 ServerApp] Creating new directory in /elliot/data
[I 2024-02-13 14:05:17.335 ServerApp] Uploading file to /elliot/data/fairbook/fairbook_events.csv
[I 2024-02-13 14:05:17.396 ServerApp] Saving file at /elliot/data/fairbook/fairbook_events.csv
[I 2024-02-13 14:05:34.689 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-13 14:06:54.030 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-13 14:10:55.039 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-13 14:12:22.798 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-13 14:12:24.551 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-13 14:12:56.018 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-13 14:14:57.052 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-13 14:16:57.116 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-13 14:18:57.164 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-13 14:20:58.007 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-13 14:22:59.014 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-13 14:50:29.304 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-13 15:02:42.552 ServerApp] Starting buffering for 426060dc-bf09-4904-ab96-c21f6cda5563:540bd110-045c-4f2c-b2e8-0eabd649efc2
[I 2024-02-13 15:02:42.562 ServerApp] Connecting to kernel 426060dc-bf09-4904-ab96-c21f6cda5563.
[I 2024-02-13 15:02:42.562 ServerApp] Restoring connection for 426060dc-bf09-4904-ab96-c21f6cda5563:540bd110-045c-4f2c-b2e8-0eabd649efc2
[W 2024-02-13 15:04:12.572 ServerApp] WebSocket ping timeout after 90009 ms.
[I 2024-02-13 15:04:17.577 ServerApp] Starting buffering for 426060dc-bf09-4904-ab96-c21f6cda5563:540bd110-045c-4f2c-b2e8-0eabd649efc2
[I 2024-02-13 15:42:25.483 ServerApp] Connecting to kernel 426060dc-bf09-4904-ab96-c21f6cda5563.
[I 2024-02-13 15:42:25.483 ServerApp] Restoring connection for 426060dc-bf09-4904-ab96-c21f6cda5563:540bd110-045c-4f2c-b2e8-0eabd649efc2
[I 2024-02-13 15:42:33.225 ServerApp] Creating new file in 
[I 2024-02-13 15:42:50.861 ServerApp] Saving file at /requirements.txt
[I 2024-02-13 15:43:00.652 ServerApp] Saving file at /requirements.txt
[I 2024-02-13 15:43:16.479 ServerApp] Saving file at /requirements.txt
[I 2024-02-13 16:21:48.372 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-13 16:23:48.416 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-13 16:25:48.450 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-13 16:27:41.764 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-13 16:28:24.064 ServerApp] Creating new directory in /elliot/results
[I 2024-02-13 16:28:34.507 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-13 16:28:47.998 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-13 16:29:26.376 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-13 16:31:27.373 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-13 16:36:50.377 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-13 16:38:50.459 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-13 16:40:27.383 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-13 16:41:31.355 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-13 16:43:19.798 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-13 16:43:31.401 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-13 16:45:17.478 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-13 16:45:20.342 ServerApp] Saving file at /Second try.ipynb
[W 2024-02-13 16:47:25.487 ServerApp] WebSocket ping timeout after 119773 ms.
[I 2024-02-13 16:47:30.497 ServerApp] Starting buffering for 426060dc-bf09-4904-ab96-c21f6cda5563:540bd110-045c-4f2c-b2e8-0eabd649efc2
[I 2024-02-14 10:44:00.359 ServerApp] 302 GET / (@127.0.0.1) 0.92ms
[I 2024-02-14 10:46:48.364 ServerApp] Connecting to kernel 426060dc-bf09-4904-ab96-c21f6cda5563.
[I 2024-02-14 10:48:48.310 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 10:50:48.895 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 11:21:22.862 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 11:24:08.029 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-14 11:24:43.826 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-14 11:24:48.249 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
2024-02-14 11:25:10.974943: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2024-02-14 11:25:10.974987: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2024-02-14 11:25:10.975019: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (alice.ia.cwi.nl): /proc/driver/nvidia/version does not exist
2024-02-14 11:25:10.975217: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-14 11:25:10.990493: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 1996120000 Hz
2024-02-14 11:25:10.997363: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3e05980 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2024-02-14 11:25:10.997420: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[I 2024-02-14 11:25:23.825 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 11:27:23.884 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 11:29:23.945 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 11:31:24.003 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 11:33:24.074 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 11:35:24.141 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 11:37:24.213 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 11:39:24.808 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 11:40:22.806 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-14 11:43:25.794 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 11:54:25.185 ServerApp] Starting buffering for 426060dc-bf09-4904-ab96-c21f6cda5563:dc1a5691-9f1f-4c33-a021-eadca197e2e6
[I 2024-02-14 11:54:25.256 ServerApp] Connecting to kernel 426060dc-bf09-4904-ab96-c21f6cda5563.
[I 2024-02-14 11:54:25.257 ServerApp] Restoring connection for 426060dc-bf09-4904-ab96-c21f6cda5563:dc1a5691-9f1f-4c33-a021-eadca197e2e6
[W 2024-02-14 11:55:55.260 ServerApp] WebSocket ping timeout after 90003 ms.
[I 2024-02-14 11:56:00.269 ServerApp] Starting buffering for 426060dc-bf09-4904-ab96-c21f6cda5563:dc1a5691-9f1f-4c33-a021-eadca197e2e6
[I 2024-02-14 12:04:18.777 ServerApp] Connecting to kernel 426060dc-bf09-4904-ab96-c21f6cda5563.
[I 2024-02-14 12:04:47.957 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-14 12:32:38.172 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-14 12:34:38.217 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-14 12:34:43.121 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-14 12:36:01.579 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-14 12:36:10.433 ServerApp] Saving file at /elliot/config_files/savvina_config.yml
[I 2024-02-14 12:36:38.162 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 12:40:38.217 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 12:42:39.166 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 12:46:41.157 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 12:50:43.144 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 12:54:45.152 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 12:58:47.127 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 13:00:48.120 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 13:04:50.134 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 13:08:52.109 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 13:12:54.123 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 13:14:55.110 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 13:18:57.097 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 13:22:59.084 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 13:27:01.097 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 13:31:03.089 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 13:33:04.078 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 13:37:06.073 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 13:41:08.083 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 13:45:10.072 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 13:49:12.064 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 13:51:13.065 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 13:55:15.138 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 13:59:16.080 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:03:16.178 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:06:54.594 ServerApp] Creating new notebook in 
[I 2024-02-14 14:06:57.773 ServerApp] Kernel started: c788e460-9f22-48ed-b62e-2a3520c3bbcf
[I 2024-02-14 14:06:58.378 ServerApp] Connecting to kernel c788e460-9f22-48ed-b62e-2a3520c3bbcf.
[I 2024-02-14 14:07:17.042 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:08:58.017 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-14 14:09:18.083 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:13:20.019 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:16:23.329 ServerApp] Copying elliot/config_files/savvina_config.yml to /elliot/config_files
[I 2024-02-14 14:17:22.048 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:19:42.909 ServerApp] Creating new directory in /elliot/data
[I 2024-02-14 14:21:24.066 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:23:25.038 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:26:39.015 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-14 14:27:27.004 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:31:28.992 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:34:41.994 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-14 14:35:30.985 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:36:43.005 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-14 14:37:41.339 ServerApp] Saving file at /elliot/config_files/pop_good1.yml
[I 2024-02-14 14:38:06.532 ServerApp] Saving file at /elliot/config_files/pop_good1.yml
[I 2024-02-14 14:38:13.996 ServerApp] Saving file at /elliot/config_files/pop_good1.yml
[I 2024-02-14 14:39:06.084 ServerApp] Saving file at /elliot/config_files/pop_good1.yml
[I 2024-02-14 14:39:33.975 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:40:09.645 ServerApp] Saving file at /elliot/config_files/pop_good1.yml
[I 2024-02-14 14:40:43.973 ServerApp] Saving file at /PopularityGood.ipynb
2024-02-14 14:40:46.397646: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-14 14:40:46.397679: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-14 14:40:50.476575: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2024-02-14 14:40:50.476613: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2024-02-14 14:40:50.476640: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (alice.ia.cwi.nl): /proc/driver/nvidia/version does not exist
2024-02-14 14:40:50.476885: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-14 14:40:50.491622: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 1996120000 Hz
2024-02-14 14:40:50.499256: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4261210 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2024-02-14 14:40:50.499304: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[I 2024-02-14 14:41:35.104 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:42:44.074 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-14 14:44:36.361 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:44:44.160 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-14 14:46:36.966 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:48:37.996 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:48:45.959 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-14 14:50:46.964 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-14 14:52:39.960 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:54:48.936 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-14 14:56:41.937 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 14:58:50.955 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-14 15:00:43.941 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 15:02:52.952 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-14 15:04:45.965 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 15:06:46.934 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-14 15:06:55.922 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-14 15:08:33.317 ServerApp] Starting buffering for c788e460-9f22-48ed-b62e-2a3520c3bbcf:099dca63-219a-417a-887b-5d901d93766c
[I 2024-02-14 15:08:33.325 ServerApp] Starting buffering for 426060dc-bf09-4904-ab96-c21f6cda5563:42d94350-08d8-4679-b93c-3a5c6af4ae54
[I 2024-02-14 15:08:33.360 ServerApp] Connecting to kernel c788e460-9f22-48ed-b62e-2a3520c3bbcf.
[I 2024-02-14 15:08:33.360 ServerApp] Restoring connection for c788e460-9f22-48ed-b62e-2a3520c3bbcf:099dca63-219a-417a-887b-5d901d93766c
[I 2024-02-14 15:08:33.434 ServerApp] Connecting to kernel 426060dc-bf09-4904-ab96-c21f6cda5563.
[I 2024-02-14 15:08:33.435 ServerApp] Restoring connection for 426060dc-bf09-4904-ab96-c21f6cda5563:42d94350-08d8-4679-b93c-3a5c6af4ae54
[W 2024-02-14 15:10:03.368 ServerApp] WebSocket ping timeout after 90007 ms.
[W 2024-02-14 15:10:03.435 ServerApp] WebSocket ping timeout after 90000 ms.
[I 2024-02-14 15:10:08.372 ServerApp] Starting buffering for c788e460-9f22-48ed-b62e-2a3520c3bbcf:099dca63-219a-417a-887b-5d901d93766c
[I 2024-02-14 15:10:08.437 ServerApp] Starting buffering for 426060dc-bf09-4904-ab96-c21f6cda5563:42d94350-08d8-4679-b93c-3a5c6af4ae54
[I 2024-02-16 15:29:19.493 ServerApp] 302 GET /?token=[secret] (@127.0.0.1) 1.95ms
[I 2024-02-16 15:33:33.752 ServerApp] Connecting to kernel c788e460-9f22-48ed-b62e-2a3520c3bbcf.
[I 2024-02-16 15:33:33.754 ServerApp] Discarding 337 buffered messages for c788e460-9f22-48ed-b62e-2a3520c3bbcf:099dca63-219a-417a-887b-5d901d93766c
[I 2024-02-16 15:33:38.883 ServerApp] Creating new notebook in 
[I 2024-02-16 15:33:40.898 ServerApp] Kernel started: 6ded6905-b045-405d-b7e8-fd98e10948a0
[I 2024-02-16 15:33:41.563 ServerApp] Connecting to kernel 6ded6905-b045-405d-b7e8-fd98e10948a0.
[I 2024-02-16 15:35:40.797 ServerApp] Saving file at /AnalyzeRecs.ipynb
[I 2024-02-16 15:41:41.859 ServerApp] Saving file at /AnalyzeRecs.ipynb
[I 2024-02-16 17:41:41.274 ServerApp] Creating new file in 
[I 2024-02-16 17:41:55.644 ServerApp] Creating new file in 
[I 2024-02-16 17:42:13.482 ServerApp] Saving file at /data_generation.py
[I 2024-02-16 17:42:28.708 ServerApp] Saving file at /modelling_mf.py
[I 2024-02-16 17:50:19.040 ServerApp] Saving file at /modelling_mf.py
[I 2024-02-16 17:50:24.990 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-16 17:51:27.725 ServerApp] Saving file at /AnalyzeRecs.ipynb
[I 2024-02-16 17:51:37.052 ServerApp] Creating new file in 
[I 2024-02-16 17:52:20.385 ServerApp] Saving file at /analysis.py
[I 2024-02-16 17:52:37.825 ServerApp] Saving file at /modelling_mf.py
[I 2024-02-16 17:52:49.568 ServerApp] Kernel restarted: 6ded6905-b045-405d-b7e8-fd98e10948a0
[I 2024-02-16 17:52:49.603 ServerApp] Starting buffering for 6ded6905-b045-405d-b7e8-fd98e10948a0:ab49c63c-75dd-4a59-9d8a-323b95c871c0
[I 2024-02-16 17:52:49.618 ServerApp] Connecting to kernel 6ded6905-b045-405d-b7e8-fd98e10948a0.
[I 2024-02-16 17:52:49.618 ServerApp] Restoring connection for 6ded6905-b045-405d-b7e8-fd98e10948a0:ab49c63c-75dd-4a59-9d8a-323b95c871c0
[I 2024-02-16 17:53:04.323 ServerApp] Creating new file in 
[I 2024-02-16 17:53:15.508 ServerApp] Saving file at /enrich.py
[I 2024-02-16 17:53:27.772 ServerApp] Saving file at /AnalyzeRecs.ipynb
[I 2024-02-16 17:54:21.325 ServerApp] Starting buffering for c788e460-9f22-48ed-b62e-2a3520c3bbcf:0f6205a9-aa9b-4c96-ae15-110b24fd5489
[I 2024-02-16 17:55:27.821 ServerApp] Saving file at /AnalyzeRecs.ipynb
[I 2024-02-16 17:56:22.272 ServerApp] Connecting to kernel c788e460-9f22-48ed-b62e-2a3520c3bbcf.
[I 2024-02-16 17:57:27.877 ServerApp] Saving file at /AnalyzeRecs.ipynb
[I 2024-02-16 17:59:10.685 ServerApp] Saving file at /AnalyzeRecs.ipynb
[I 2024-02-16 18:08:11.635 ServerApp] Starting buffering for 6ded6905-b045-405d-b7e8-fd98e10948a0:ab49c63c-75dd-4a59-9d8a-323b95c871c0
[I 2024-02-16 18:08:11.647 ServerApp] Starting buffering for c788e460-9f22-48ed-b62e-2a3520c3bbcf:845e0f7f-cb74-428f-bea5-81e490f659fe
[I 2024-02-20 13:52:23.357 ServerApp] Connecting to kernel c788e460-9f22-48ed-b62e-2a3520c3bbcf.
[I 2024-02-20 13:52:35.421 ServerApp] Connecting to kernel 6ded6905-b045-405d-b7e8-fd98e10948a0.
[I 2024-02-20 13:53:19.994 ServerApp] Saving file at /elliot/config_files/pop_good1.yml
[W 2024-02-20 13:53:43.363 ServerApp] delete /elliot/results/pop_good1/performance
[W 2024-02-20 13:53:43.373 ServerApp] delete /elliot/results/pop_good1/recs
[W 2024-02-20 13:53:43.377 ServerApp] delete /elliot/results/pop_good1/weights
[I 2024-02-20 13:53:50.251 ServerApp] Kernel restarted: c788e460-9f22-48ed-b62e-2a3520c3bbcf
[I 2024-02-20 13:53:50.261 ServerApp] Starting buffering for c788e460-9f22-48ed-b62e-2a3520c3bbcf:af5d0ac1-1da8-4efe-a2f2-2d760a9f67fe
[I 2024-02-20 13:53:50.279 ServerApp] Connecting to kernel c788e460-9f22-48ed-b62e-2a3520c3bbcf.
[I 2024-02-20 13:53:50.279 ServerApp] Restoring connection for c788e460-9f22-48ed-b62e-2a3520c3bbcf:af5d0ac1-1da8-4efe-a2f2-2d760a9f67fe
2024-02-20 13:54:04.465987: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 13:54:04.466042: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 13:54:08.522210: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2024-02-20 13:54:08.522255: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2024-02-20 13:54:08.522294: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (alice.ia.cwi.nl): /proc/driver/nvidia/version does not exist
2024-02-20 13:54:08.522504: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-20 13:54:08.537103: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 1996120000 Hz
2024-02-20 13:54:08.544742: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x48556d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2024-02-20 13:54:08.544804: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[I 2024-02-20 13:54:23.332 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-20 13:56:23.924 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-20 13:56:36.920 ServerApp] Saving file at /AnalyzeRecs.ipynb
[I 2024-02-20 13:57:34.550 ServerApp] Saving file at /elliot/config_files/pop_good1.yml
[I 2024-02-20 13:58:23.981 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-20 13:58:38.524 ServerApp] Connecting to kernel 426060dc-bf09-4904-ab96-c21f6cda5563.
[I 2024-02-20 13:58:38.525 ServerApp] Discarding 6873 buffered messages for 426060dc-bf09-4904-ab96-c21f6cda5563:42d94350-08d8-4679-b93c-3a5c6af4ae54
[I 2024-02-20 14:00:24.050 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-20 14:00:38.923 ServerApp] Saving file at /Second try.ipynb
[I 2024-02-20 14:02:24.102 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-20 14:04:24.164 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-20 14:06:24.232 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-20 14:08:24.300 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-20 14:09:03.907 ServerApp] Saving file at /AnalyzeRecs.ipynb
[I 2024-02-20 14:11:03.953 ServerApp] Saving file at /AnalyzeRecs.ipynb
2024-02-20 14:12:22.740347: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:12:22.740389: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 14:12:22.955121: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:12:22.955171: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 14:12:23.188817: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:12:23.188862: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 14:12:23.427059: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:12:23.427085: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[I 2024-02-20 14:13:04.015 ServerApp] Saving file at /AnalyzeRecs.ipynb
2024-02-20 14:13:25.394264: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:13:25.394314: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 14:13:25.633573: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:13:25.633611: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 14:13:25.786792: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:13:25.786856: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 14:13:26.033897: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:13:26.033933: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[I 2024-02-20 14:14:11.109 ServerApp] Copying elliot/config_files/pop_good1.yml to /elliot/config_files
[I 2024-02-20 14:14:54.224 ServerApp] Saving file at /elliot/config_files/pop_bad1.yml
[I 2024-02-20 14:15:04.916 ServerApp] Saving file at /AnalyzeRecs.ipynb
[I 2024-02-20 14:15:10.092 ServerApp] Creating new directory in /elliot/data
[I 2024-02-20 14:16:09.960 ServerApp] Uploading file to /elliot/data/popularity_bad/popularity_bad_fold_1_test.csv
[I 2024-02-20 14:16:10.045 ServerApp] Uploading file to /elliot/data/popularity_bad/popularity_bad_fold_1_train.csv
[I 2024-02-20 14:16:10.091 ServerApp] Saving file at /elliot/data/popularity_bad/popularity_bad_fold_1_train.csv
[I 2024-02-20 14:16:14.126 ServerApp] Saving file at /PopularityGood.ipynb
[I 2024-02-20 14:16:19.105 ServerApp] Starting buffering for 426060dc-bf09-4904-ab96-c21f6cda5563:33233896-4df4-4e6a-9314-21567ac799c1
[I 2024-02-20 14:16:24.247 ServerApp] Copying PopularityGood.ipynb to 
[I 2024-02-20 14:16:34.223 ServerApp] Kernel started: 0fca18a9-64d1-425b-b84e-e65f6cc50c8f
[I 2024-02-20 14:16:34.769 ServerApp] Connecting to kernel 0fca18a9-64d1-425b-b84e-e65f6cc50c8f.
2024-02-20 14:17:28.007588: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:17:28.007630: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[I 2024-02-20 14:17:31.234 ServerApp] Saving file at /PopularityBad.ipynb
2024-02-20 14:17:32.087474: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2024-02-20 14:17:32.087515: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2024-02-20 14:17:32.087548: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (alice.ia.cwi.nl): /proc/driver/nvidia/version does not exist
2024-02-20 14:17:32.087742: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-20 14:17:32.104147: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 1996120000 Hz
2024-02-20 14:17:32.111719: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x46043b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2024-02-20 14:17:32.111775: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[I 2024-02-20 14:19:05.945 ServerApp] Saving file at /AnalyzeRecs.ipynb
[I 2024-02-20 14:19:31.894 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 14:21:06.940 ServerApp] Saving file at /AnalyzeRecs.ipynb
[I 2024-02-20 14:21:31.946 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 14:23:31.995 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 14:25:32.048 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 14:27:32.105 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 14:29:32.158 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 14:31:32.223 ServerApp] Saving file at /PopularityBad.ipynb
2024-02-20 14:33:07.874630: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:33:07.874678: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 14:33:08.159733: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:33:08.159769: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 14:33:08.388445: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:33:08.388482: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 14:33:08.545042: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:33:08.545079: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 14:33:40.098386: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:33:40.098433: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 14:33:40.358139: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:33:40.358175: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 14:33:40.572527: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:33:40.572562: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 14:33:40.747168: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:33:40.747215: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[I 2024-02-20 14:33:48.977 ServerApp] Saving file at /AnalyzeRecs.ipynb
2024-02-20 14:34:42.442556: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:34:42.442603: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 14:34:42.693176: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:34:42.693211: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 14:34:42.879462: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:34:42.879503: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 14:34:43.109840: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 14:34:43.109871: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[I 2024-02-20 14:35:49.072 ServerApp] Saving file at /AnalyzeRecs.ipynb
[W 2024-02-20 15:15:34.429 ServerApp] delete /elliot/results/pop_bad1/performance
[W 2024-02-20 15:15:34.436 ServerApp] delete /elliot/results/pop_bad1/recs
[W 2024-02-20 15:15:34.440 ServerApp] delete /elliot/results/pop_bad1/weights
[I 2024-02-20 15:15:57.806 ServerApp] Saving file at /elliot/config_files/pop_bad1.yml
[I 2024-02-20 15:16:25.642 ServerApp] Saving file at /elliot/config_files/pop_bad1.yml
[I 2024-02-20 15:17:03.816 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 15:19:03.857 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 15:23:13.033 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 15:24:00.448 ServerApp] Starting buffering for 0fca18a9-64d1-425b-b84e-e65f6cc50c8f:c48145ed-125f-47d9-a953-1688e72ab761
[I 2024-02-20 15:24:12.264 ServerApp] Connecting to kernel 0fca18a9-64d1-425b-b84e-e65f6cc50c8f.
[I 2024-02-20 15:24:18.336 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 15:24:46.256 ServerApp] Saving file at /AnalyzeRecs.ipynb
[I 2024-02-20 15:24:46.712 ServerApp] Starting buffering for 6ded6905-b045-405d-b7e8-fd98e10948a0:3635a9f4-4abd-4aa9-8e9f-19aa8526c453
[I 2024-02-20 15:24:48.805 ServerApp] Connecting to kernel 6ded6905-b045-405d-b7e8-fd98e10948a0.
[I 2024-02-20 15:24:59.042 ServerApp] Kernel interrupted: 0fca18a9-64d1-425b-b84e-e65f6cc50c8f
[I 2024-02-20 15:24:59.796 ServerApp] Kernel interrupted: 0fca18a9-64d1-425b-b84e-e65f6cc50c8f
[I 2024-02-20 15:25:00.020 ServerApp] Kernel interrupted: 0fca18a9-64d1-425b-b84e-e65f6cc50c8f
[I 2024-02-20 15:25:00.171 ServerApp] Kernel interrupted: 0fca18a9-64d1-425b-b84e-e65f6cc50c8f
[I 2024-02-20 15:25:00.338 ServerApp] Kernel interrupted: 0fca18a9-64d1-425b-b84e-e65f6cc50c8f
[I 2024-02-20 15:25:02.418 ServerApp] Kernel interrupted: 0fca18a9-64d1-425b-b84e-e65f6cc50c8f
[I 2024-02-20 15:25:07.270 ServerApp] Starting buffering for 0fca18a9-64d1-425b-b84e-e65f6cc50c8f:4f5933b4-6406-46b5-848f-8e772c498cab
[I 2024-02-20 15:25:09.095 ServerApp] Connecting to kernel 0fca18a9-64d1-425b-b84e-e65f6cc50c8f.
[I 2024-02-20 15:25:24.803 ServerApp] Kernel restarted: 0fca18a9-64d1-425b-b84e-e65f6cc50c8f
[I 2024-02-20 15:25:24.815 ServerApp] Starting buffering for 0fca18a9-64d1-425b-b84e-e65f6cc50c8f:f792ddf3-3d42-47e8-99ed-bcf922a48a4a
[I 2024-02-20 15:25:24.833 ServerApp] Connecting to kernel 0fca18a9-64d1-425b-b84e-e65f6cc50c8f.
[I 2024-02-20 15:25:24.833 ServerApp] Restoring connection for 0fca18a9-64d1-425b-b84e-e65f6cc50c8f:f792ddf3-3d42-47e8-99ed-bcf922a48a4a
[W 2024-02-20 15:25:31.520 ServerApp] delete /elliot/results/pop_bad1/recs
[W 2024-02-20 15:25:31.527 ServerApp] delete /elliot/results/pop_bad1/weights
[W 2024-02-20 15:25:31.532 ServerApp] delete /elliot/results/pop_bad1/performance
2024-02-20 15:25:43.236657: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 15:25:43.236702: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-20 15:25:47.298885: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2024-02-20 15:25:47.298929: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2024-02-20 15:25:47.298963: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (alice.ia.cwi.nl): /proc/driver/nvidia/version does not exist
2024-02-20 15:25:47.299157: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-20 15:25:47.313501: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 1996120000 Hz
2024-02-20 15:25:47.321337: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x49f5c10 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2024-02-20 15:25:47.321401: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[I 2024-02-20 15:26:36.732 ServerApp] Starting buffering for c788e460-9f22-48ed-b62e-2a3520c3bbcf:af5d0ac1-1da8-4efe-a2f2-2d760a9f67fe
[I 2024-02-20 15:26:48.852 ServerApp] Saving file at /AnalyzeRecs.ipynb
[I 2024-02-20 15:27:09.812 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 15:29:10.805 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 15:31:11.802 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 15:33:12.802 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 15:37:14.800 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 15:41:16.791 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 15:43:16.844 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 15:47:16.885 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 15:51:16.932 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 15:55:16.977 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 15:57:03.682 ServerApp] Creating new notebook in 
[I 2024-02-20 15:57:06.195 ServerApp] Kernel started: ab1d5d6c-939e-4dd0-8ee1-6fa5bc562eb0
[I 2024-02-20 15:57:06.804 ServerApp] Connecting to kernel ab1d5d6c-939e-4dd0-8ee1-6fa5bc562eb0.
2024-02-20 15:57:24.896051: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-02-20 15:57:24.896087: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[I 2024-02-20 15:59:06.095 ServerApp] Saving file at /NGCFTest.ipynb
[I 2024-02-20 15:59:18.768 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 16:01:06.140 ServerApp] Saving file at /NGCFTest.ipynb
[I 2024-02-20 16:03:06.191 ServerApp] Saving file at /NGCFTest.ipynb
[I 2024-02-20 16:03:20.756 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 16:07:21.751 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 16:09:06.747 ServerApp] Saving file at /NGCFTest.ipynb
[I 2024-02-20 16:11:23.752 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 16:15:25.741 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 16:17:26.752 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 16:21:28.744 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 16:24:04.735 ServerApp] Saving file at /NGCFTest.ipynb
[I 2024-02-20 16:25:30.739 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 16:27:31.741 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 16:29:32.729 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 16:33:34.721 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 16:35:30.430 ServerApp] Kernel interrupted: 0fca18a9-64d1-425b-b84e-e65f6cc50c8f
[I 2024-02-20 16:35:33.024 ServerApp] Kernel interrupted: 0fca18a9-64d1-425b-b84e-e65f6cc50c8f
[I 2024-02-20 16:35:33.268 ServerApp] Kernel interrupted: 0fca18a9-64d1-425b-b84e-e65f6cc50c8f
[I 2024-02-20 16:35:33.469 ServerApp] Kernel interrupted: 0fca18a9-64d1-425b-b84e-e65f6cc50c8f
[I 2024-02-20 16:35:33.619 ServerApp] Kernel interrupted: 0fca18a9-64d1-425b-b84e-e65f6cc50c8f
[I 2024-02-20 16:35:33.766 ServerApp] Kernel interrupted: 0fca18a9-64d1-425b-b84e-e65f6cc50c8f
[I 2024-02-20 16:35:34.767 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 16:35:38.713 ServerApp] Saving file at /PopularityBad.ipynb
[I 2024-02-20 16:35:39.710 ServerApp] Kernel restarted: 0fca18a9-64d1-425b-b84e-e65f6cc50c8f
[I 2024-02-20 16:35:39.789 ServerApp] Starting buffering for 0fca18a9-64d1-425b-b84e-e65f6cc50c8f:f792ddf3-3d42-47e8-99ed-bcf922a48a4a
[I 2024-02-20 16:35:39.803 ServerApp] Connecting to kernel 0fca18a9-64d1-425b-b84e-e65f6cc50c8f.
[I 2024-02-20 16:35:39.803 ServerApp] Restoring connection for 0fca18a9-64d1-425b-b84e-e65f6cc50c8f:f792ddf3-3d42-47e8-99ed-bcf922a48a4a
[I 2024-02-20 16:35:40.572 ServerApp] Saving file at /NGCFTest.ipynb
[I 2024-02-20 16:35:41.970 ServerApp] Saving file at /AnalyzeRecs.ipynb
[I 2024-02-20 16:35:43.142 ServerApp] Starting buffering for ab1d5d6c-939e-4dd0-8ee1-6fa5bc562eb0:6cbaec55-d402-4e36-a8c6-75f96f0907a9
[I 2024-02-20 16:35:43.493 ServerApp] Starting buffering for 0fca18a9-64d1-425b-b84e-e65f6cc50c8f:f792ddf3-3d42-47e8-99ed-bcf922a48a4a
[I 2024-02-20 16:35:43.904 ServerApp] Starting buffering for 6ded6905-b045-405d-b7e8-fd98e10948a0:602c06d9-48d2-49a8-841c-a5cc1f2a0328
[I 2024-03-15 15:01:04.142 ServerApp] Shutting down on /api/shutdown request.
[I 2024-03-15 15:01:04.162 ServerApp] Shutting down 5 extensions
[I 2024-03-15 15:01:04.168 ServerApp] Shutting down 6 kernels
[I 2024-03-15 15:01:04.188 ServerApp] Kernel shutdown: 710d78a4-6ba7-40ab-ab52-dc24877f2249
[I 2024-03-15 15:01:04.203 ServerApp] Kernel shutdown: 6ded6905-b045-405d-b7e8-fd98e10948a0
[I 2024-03-15 15:01:04.216 ServerApp] Kernel shutdown: c788e460-9f22-48ed-b62e-2a3520c3bbcf
[I 2024-03-15 15:01:04.224 ServerApp] Kernel shutdown: 0fca18a9-64d1-425b-b84e-e65f6cc50c8f
[I 2024-03-15 15:01:04.232 ServerApp] Kernel shutdown: 426060dc-bf09-4904-ab96-c21f6cda5563
[I 2024-03-15 15:01:04.237 ServerApp] Kernel shutdown: ab1d5d6c-939e-4dd0-8ee1-6fa5bc562eb0
